name: TruffleHog Secrets Scan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
